name: Build and deploy

on:
  push:
    branches: [ "main" ]

env:
  AWS_ACCOUNT_ID: "550816839465"
  AWS_REGION: "eu-west-2"
  BRICKS_CLIENT: "pharmareview"

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::550816839465:role/GitHub
          role-session-name: GitHubActions
          aws-region: eu-west-2
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.BRICKS_CLIENT }}-test-ecr:cermine.${{ github.RUN_NUMBER }}
          cache-from: type=gha,scope=${{ github.ref_name }}-cermine
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-cermine
  